"""
GST Compliance, Filing, and Reconciliation State Generator.

Simulates statutory filing events and reconciles multi-hop supply relationships:
Vendor -> Invoice -> GSTR-1 -> GSTR-2B -> Purchase Register -> GSTR-3B -> E-Invoice -> E-Way Bill.
"""

from datetime import date, timedelta
from decimal import Decimal
import random
from typing import List, Dict, Tuple, Optional

from backend.data.schema import (
    Invoice, Filing, Reconciliation, ReconciliationStatus, TWOPLACES, DataSource
)
from backend.data.synthetic.profiles import PROFILES, VendorBehaviorProfile


class ComplianceGenerator:
    """Simulates realistic return filing and multi-source reconciliation statuses."""

    def __init__(self, seed: int = 42):
        self.rng = random.Random(seed)

    def generate_filings_for_period(
        self,
        vendor_id: str,
        tax_period: str,
        profile: VendorBehaviorProfile
    ) -> Filing:
        """
        Determines GSTR-1 and GSTR-3B filing timeliness and status for a given month.
        Statutory deadline for GSTR-1: 11th of subsequent month.
        Statutory deadline for GSTR-3B: 20th of subsequent month.
        """
        year, month = map(int, tax_period.split("-"))
        # Subsequent month calculation
        sub_month = (month % 12) + 1
        sub_year = year + (1 if month == 12 else 0)

        # Decide if GSTR-1 was filed
        gstr1_filed = self.rng.random() >= profile.missing_gstr1_probability
        # Decide if GSTR-3B was filed (unpaid tax chain)
        gstr3b_filed = self.rng.random() >= profile.missing_gstr3b_probability

        # Filing delay calculation
        delay_days = max(0, int(round(self.rng.gauss(profile.filing_delay_mean, profile.filing_delay_std))))

        gstr1_filing_date = None
        if gstr1_filed:
            gstr1_deadline = date(sub_year, sub_month, 11)
            gstr1_filing_date = gstr1_deadline + timedelta(days=delay_days)

        gstr3b_filing_date = None
        if gstr3b_filed:
            gstr3b_deadline = date(sub_year, sub_month, 20)
            gstr3b_filing_date = gstr3b_deadline + timedelta(days=delay_days)

        return Filing(
            vendor_id=vendor_id,
            tax_period=tax_period,
            gstr1_filed=gstr1_filed,
            gstr1_filing_date=gstr1_filing_date,
            gstr3b_filed=gstr3b_filed,
            gstr3b_filing_date=gstr3b_filing_date,
            filing_delay_days=delay_days,
            data_source=DataSource.SYNTHETIC
        )

    def generate_reconciliation_record(
        self,
        invoice: Invoice,
        filing: Filing,
        profile: VendorBehaviorProfile
    ) -> Reconciliation:
        """
        Derives the 3-way reconciliation state between:
        1. Supplier GSTR-1
        2. Auto-generated Buyer GSTR-2B
        3. Buyer Purchase Register (PR)
        plus e-Invoice and e-Way Bill compliance.
        """
        # GSTR-1 presence: governed by whether supplier filed GSTR-1 and did not omit this invoice
        if not filing.gstr1_filed:
            gstr1_present = False
        else:
            gstr1_present = self.rng.random() >= (profile.mismatch_probability * 0.4)

        # GSTR-2B presence: GSTR-2B is auto-generated by the GST portal based on GSTR-1
        # If GSTR-1 was filed on-time, it appears in 2B. If supplier didn't file, buyer still
        # has it in Purchase Register, causing a missing-in-GSTR-1 mismatch.
        gstr2b_present = gstr1_present

        # Purchase Register: Buyer booked the invoice (present in ~98% of standard business transactions)
        # Occasionally buyer forgot to record an invoice in books (<2%)
        purchase_register_present = self.rng.random() >= 0.02

        # e-Invoice IRN presence (e-Invoicing mandatory for B2B)
        einvoice_present = self.rng.random() >= profile.missing_einvoice_probability

        # e-Way Bill: Mandatory for consignment value > 50,000 INR
        if invoice.invoice_value > Decimal("50000.00"):
            ewaybill_present = self.rng.random() >= profile.missing_ewaybill_probability
        else:
            ewaybill_present = True

        # Check for field mismatches
        tax_amount_match = invoice.anomaly_type != "TAX_MISMATCH"
        taxable_value_match = invoice.anomaly_type != "TAXABLE_VALUE_MISMATCH"
        hsn_match = invoice.anomaly_type != "HSN_MISMATCH"
        date_match = invoice.anomaly_type != "DATE_MISMATCH"

        # Determine overall reconciliation status
        status = ReconciliationStatus.MATCHED
        discrepancy = Decimal("0.00")

        if invoice.is_duplicate:
            status = ReconciliationStatus.DUPLICATE_INVOICE
            discrepancy = invoice.total_tax
        elif not gstr1_present and purchase_register_present:
            status = ReconciliationStatus.MISSING_IN_GSTR1
            discrepancy = invoice.total_tax
        elif gstr1_present and not purchase_register_present:
            status = ReconciliationStatus.MISSING_IN_PR
            discrepancy = invoice.total_tax
        elif not tax_amount_match:
            status = ReconciliationStatus.TAX_MISMATCH
            discrepancy = Decimal("1500.00")  # Nominal discrepancy amount
        elif not taxable_value_match:
            status = ReconciliationStatus.TAXABLE_VALUE_MISMATCH
            discrepancy = Decimal("5000.00")
        elif not hsn_match:
            status = ReconciliationStatus.HSN_MISMATCH
        elif not date_match:
            status = ReconciliationStatus.DATE_MISMATCH
        elif not filing.gstr3b_filed and gstr1_present:
            status = ReconciliationStatus.UNPAID_TAX_CHAIN
            discrepancy = invoice.total_tax
        elif filing.filing_delay_days > 15:
            status = ReconciliationStatus.LATE_FILING

        return Reconciliation(
            invoice_id=invoice.invoice_id,
            vendor_id=invoice.vendor_id,
            tax_period=invoice.tax_period,
            gstr1_present=gstr1_present,
            gstr2b_present=gstr2b_present,
            purchase_register_present=purchase_register_present,
            tax_amount_match=tax_amount_match,
            taxable_value_match=taxable_value_match,
            hsn_match=hsn_match,
            date_match=date_match,
            einvoice_present=einvoice_present,
            ewaybill_present=ewaybill_present,
            reconciliation_status=status,
            discrepancy_amount=discrepancy
        )
